__default__:
    partition: "holy-info"
    time: 30-00:00:00
    nodes: 1
    output: "logs/slurm-%j.out"
    #error: "logs/slurm-%j.err"


###
# bam2vcf_gatk
###

bam2gvcf: 
    partition: "holy-info"


###
# bam2vcf_fb
###

bam2vcf: 
    partition: "holy-info"
    #mem: 5000 # MEMORY IS SPECIFIED WITHIN RULE, TO INCREASE WITH ATTEMPTS
